name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: "Create env file"
        run: |
          touch .env
          echo VITE_API=${{ secrets.VITE_API }} >> .env
          cat .env

      - name: "Install dependencies"
        run: npm ci

      - name: "Build"
        run: npm run build

      - name: "Firebase deploy"
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_DICTIONARY_OF_NEOLOGISMS }}"
          channelId: live
          projectId: dictionary-of-neologisms
